Description of prt_get_defaults
Home > . > prt_get_defaults.m
prt_get_defaults
PURPOSE
Get/set the defaults values associated with an identifier
SYNOPSIS
function varargout = prt_get_defaults(defstr, varargin)
DESCRIPTION
 Get/set the defaults values associated with an identifier
 FORMAT defaults = prt_get_defaults
 Return the global "defaults" variable defined in prt_defaults.m.
 FORMAT defval = prt_get_defaults(defstr)
 Return the defaults value associated with identifier "defstr".
 Currently, this is a '.' subscript reference into the global
 "prt_def" variable defined in prt_defaults.m.
 FORMAT prt_get_defaults(defstr, defval)
 Sets the defaults value associated with identifier "defstr". The new
 defaults value applies immediately to:
 * new modules in batch jobs
 * modules in batch jobs that have not been saved yet
 This value will not be saved for future sessions of PRoNTo. To make
 persistent changes, edit prt_defaults.m.
 The structure and content of this file are largely inspired by SPM &
 Matlabbatch.
 http://www.fil.ion.ucl.ac.uk/spm
 http://sourceforge.net/projects/matlabbatch/
__________________________________________________________________________
 Copyright (C) 2011 Machine Learning & Neuroimaging Laboratory
CROSS-REFERENCE INFORMATION
This function calls:
prt_defaults Sets the defaults which are used by the Pattern Recognition for
This function is called by:
prt_check_design FORMAT [conds] = prt_check_design(cond,tr,units,hrfoverlap)
prt_data_conditions PRT_DATA_CONDITIONS M-file for prt_data_conditions.fig
prt_data_modality PRT_DATA_MODALITY M-file for prt_data_modality.fig
prt_data_review PRT_DATA_REVIEW M-file for prt_data_review.fig
prt_fs_modality Function to build file arrays containing the (linearly detrended) data
prt_permutation Function to compute permutation test
prt_text_input PRT_TEXT_INPUT M-file for prt_text_input.fig
prt_ui_compute_weights PRT_UI_COMPUTE_WEIGHTS M-file for prt_ui_compute_weights.fig
prt_ui_custom_CV PRT_UI_CUSTOM_CV M-file for prt_ui_custom_CV.fig
prt_ui_cv_model PRT_UI_CV_MODEL M-file for prt_ui_cv_model.fig
prt_ui_design PRT_UI_DESIGN M-file for prt_ui_design.fig
prt_ui_disp_weights PRT_UI_DISP_WEIGHTS MATLAB code for prt_ui_disp_weights.fig
prt_ui_main PRT_UI_MAIN M-file for prt_ui_main.fig
prt_ui_model PRT_UI_KERNEL_CONSTRUCTION M-file for prt_ui_kernel_construction.fig
prt_ui_prepare_data PRT_UI_KERNEL MATLAB code for prt_ui_kernel.fig
prt_ui_prepare_datamod PRT_UI_KERNEL_MODALITY M-file for prt_ui_kernel_modality.fig
prt_ui_results PRT_UI_RESULTS MATLAB code for prt_ui_results.fig
prt_ui_results_ROI PRT_UI_RESULTS_ROI M-file for prt_ui_results_ROI.fig
prt_ui_results_stats PRT_UI_RESULTS_STATS MATLAB code for prt_ui_results_stats.fig
prt_ui_reviewCV PRT_UI_REVIEWCV M-file for prt_ui_reviewCV.fig
prt_ui_reviewmodel PRT_UI_REVIEWMODEL M-file for prt_ui_reviewmodel.fig
prt_ui_select_class PRT_UI_SELECT_CLASS M-file for prt_ui_select_class.fig
prt_ui_select_reg PRT_UI_SELECT_REG M-file for prt_ui_select_reg.fig
prt_ui_specify_CV_basis PRT_UI_SPECIFY_CV_BASIS M-file for prt_ui_specify_CV_basis.fig
prt_ui_stats PRT_UI_STATS MATLAB code for prt_ui_stats.fig
prt_ui_sure PRT_UI_SURE M-file for prt_ui_sure.fig
SOURCE CODE
function varargout = prt_get_defaults(defstr, varargin)
% Get/set the defaults values associated with an identifier
%
% FORMAT defaults = prt_get_defaults
% Return the global "defaults" variable defined in prt_defaults.m.
%
% FORMAT defval = prt_get_defaults(defstr)
% Return the defaults value associated with identifier "defstr".
% Currently, this is a '.' subscript reference into the global
% "prt_def" variable defined in prt_defaults.m.
%
% FORMAT prt_get_defaults(defstr, defval)
% Sets the defaults value associated with identifier "defstr". The new
% defaults value applies immediately to:
% * new modules in batch jobs
% * modules in batch jobs that have not been saved yet
% This value will not be saved for future sessions of PRoNTo. To make
% persistent changes, edit prt_defaults.m.
%
% The structure and content of this file are largely inspired by SPM &
% Matlabbatch.
% http://www.fil.ion.ucl.ac.uk/spm
% http://sourceforge.net/projects/matlabbatch/
%__________________________________________________________________________
% Copyright (C) 2011 Machine Learning & Neuroimaging Laboratory
% Originally written by Volkmar Glauche
% Then modified for use with the PRoNTo toolbox by Christophe Phillips
% $Id$
global prt_def;
if isempty(prt_def)
    prt_defaults;
end
if nargin == 0
    varargout{1} = prt_def;
    return
end
% construct subscript reference struct from dot delimited tag string
tags = textscan(defstr,'%s', 'delimiter','.');
subs = struct('type','.','subs',tags{1}');
if nargin == 1
    varargout{1} = subsref(prt_def, subs);
else
    prt_def = subsasgn(prt_def, subs, varargin{1});
end